import createClient from "openapi-fetch";
import type { paths } from "../lib/api/v1"; // generated by openapi-typescript

const client = createClient<paths>({ baseUrl: "http://localhost:5107/" });

export const userListFetch = await client.GET("/api/Users", {
});

export const userWithAdressFetch = (id: number) => client.GET("/api/Users/{id}",{
    params:{
        path: { id: id},
        query: undefined,
    }
})